// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enmmulxburptgmzsmeja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubW11bHhidXJwdGdtenNtZWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTQ3NDMsImV4cCI6MjA1NjU5MDc0M30.Yqh1mAa1qCoIBgzKhRL5TAChLSE2Zjzu9A55BNbJlSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);